/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialog;

import javax.swing.DefaultListModel;
import projet.projet;

/**
 *
 * @author vincent
 */
public class ProjectSelectionDial extends javax.swing.JDialog {

    /**
     * Creates new form ProjectSelectionDial
     */
    DefaultListModel dlm;
    String bestProject;
    public ProjectSelectionDial(java.awt.Frame parent, boolean modal,DefaultListModel lm) {
        super(parent, modal);
        dlm = lm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        selectionLabel = new javax.swing.JLabel();
        npvRB = new javax.swing.JRadioButton();
        irrRB = new javax.swing.JRadioButton();
        timeRB = new javax.swing.JRadioButton();
        bestProjectLabel = new javax.swing.JLabel();
        bestProjectTF = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        selectionLabel.setText("Critère de sélection :");
        getContentPane().add(selectionLabel, new java.awt.GridBagConstraints());

        buttonGroup1.add(npvRB);
        npvRB.setText("NPV");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(npvRB, gridBagConstraints);

        buttonGroup1.add(irrRB);
        irrRB.setText("IRR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(irrRB, gridBagConstraints);

        buttonGroup1.add(timeRB);
        timeRB.setText("Délai de récupération");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(timeRB, gridBagConstraints);

        bestProjectLabel.setText("meilleur projet : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(bestProjectLabel, gridBagConstraints);

        bestProjectTF.setEditable(false);
        bestProjectTF.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(bestProjectTF, gridBagConstraints);

        searchButton.setText("Rechercher");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(searchButton, gridBagConstraints);

        closeButton.setText("Quitter");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(closeButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        getContentPane().add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 12, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        int bp = -1;
        if(npvRB.isSelected())
        {
            double bestNPV=0;
            projet project;
            for(int i=0;i<dlm.getSize();i++)
            {
                project = (projet)dlm.get(i);
                if(project.getNPV()>bestNPV)
                {
                    bestNPV = project.getNPV();
                    bp = i;
                }
            }
        }
        else if(irrRB.isSelected())
        {
            double bestIRR=0;
            projet project;
            for(int i=0;i<dlm.getSize();i++)
            {
                project = (projet)dlm.get(i);
                if(project.getNPV()>bestIRR)
                {
                    bestIRR = project.getNPV();
                    bp = i;
                }
            }
        }
        else if(timeRB.isSelected())
        {
            bp=1000;
            projet project;
            int anneePayback=-1;
            for(int i=0;i<dlm.getSize();i++)
            {
                project = (projet)dlm.get(i);
                double somme = 0;
                double invest = project.getCashflow(0);
                for(int j=1;j<=project.getPeriode();j++)
                {
                    somme += project.getCashflow(j);
                    if((invest + somme)<0)
                        anneePayback = j+1;
                }
                if(anneePayback<bp)
                    bp = i;
            }
            
        }
        else{return;}
        
        projet bProject = (projet)dlm.get(bp);
        bestProjectTF.setText("projet n°"+(bp+1)+" ("+bProject.getName()+")");
    }//GEN-LAST:event_searchButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectSelectionDial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectSelectionDial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectSelectionDial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectSelectionDial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectSelectionDial dialog = new ProjectSelectionDial(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestProjectLabel;
    private javax.swing.JTextField bestProjectTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeButton;
    private javax.swing.JRadioButton irrRB;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton npvRB;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel selectionLabel;
    private javax.swing.JRadioButton timeRB;
    // End of variables declaration//GEN-END:variables
}
